#!/usr/bin/env python3
"""
Generate the empty stub libraries that headless Blender needs in a slim
container (no X11/GL stack, no way to apt-install it).

`bpy` is a full Blender build, so its DSOs still reference GLX/EGL, xkbcommon,
Xi, Xfixes, ICE/SM entry points.  Nothing in the modelling/export path ever
*calls* them, they only have to exist for the dynamic linker.  This tool:

  1. asks ldd which libraries bpy cannot find,
  2. collects the symbols nobody provides (excluding libc/libstdc++/Python's),
  3. compiles one stub .so per missing library, exporting every such symbol,
  4. retries `import bpy` and keeps adding symbols until it loads.

Run it from tools/setup_blender_env.sh; it is idempotent and caches its symbol
list in ~/.gfxstub/symbols.txt so re-runs are instant.
"""

from __future__ import annotations

import glob
import os
import subprocess
import sys

EXCLUDE_PREFIX = ("Py", "_Py", "__cxa", "__gxx", "_Z", "__libc", "__vdso", "_init", "_fini")
ALWAYS_STUB = {"libGL.so.1", "libxkbcommon.so.0", "libXi.so.6", "libXfixes.so.3",
               "libXrender.so.1", "libICE.so.6", "libSM.so.6"}
MAX_ROUNDS = 40


def sh(cmd: str) -> str:
    return subprocess.run(cmd, shell=True, capture_output=True, text=True).stdout


def nm_undefined(path: str) -> set[str]:
    out = sh(f"nm -D --undefined-only {path!r} 2>/dev/null")
    syms = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] in ("U", "w"):
            syms.add(parts[1].split("@")[0])
    return syms


def nm_defined(path: str) -> set[str]:
    out = sh(f"nm -D --defined-only {path!r} 2>/dev/null")
    syms = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 3:
            syms.add(parts[2].split("@")[0])
        elif len(parts) >= 2:
            syms.add(parts[1].split("@")[0])
    return syms


def scan(bpy_dir: str, python_bin: str):
    """Return (missing library sonames, symbols no loadable library provides)."""
    targets = [os.path.join(bpy_dir, "__init__.so")]
    targets += sorted(glob.glob(os.path.join(bpy_dir, "lib", "*.so")))
    missing_libs: set[str] = set()
    resolved: set[str] = set()
    undefined: set[str] = set()
    for t in targets:
        for line in sh(f"ldd -r {t!r} 2>&1").splitlines():
            line = line.strip()
            if line.endswith("not found"):
                missing_libs.add(line.split()[0])
            elif "=> /" in line:
                resolved.add(line.split()[2])
        undefined |= nm_undefined(t)

    provided: set[str] = set()
    for lib in sorted(set(resolved) | {os.path.realpath(python_bin)}):
        provided |= nm_defined(lib)

    want = {s for s in undefined - provided if not s.startswith(EXCLUDE_PREFIX)}
    return missing_libs, want


def build(stub_dir: str, libs: set[str], syms: set[str]):
    os.makedirs(stub_dir, exist_ok=True)
    cache = os.path.join(stub_dir, "symbols.txt")
    have = set()
    if os.path.exists(cache):
        with open(cache) as fh:
            have = {line.strip() for line in fh if line.strip()}
    all_syms = sorted(have | syms)
    with open(cache, "w") as fh:
        fh.write("\n".join(all_syms) + "\n")

    with open(os.path.join(stub_dir, "stubs.c"), "w") as fh:
        fh.write("/* Auto-generated by tools/gfx_stubs.py -- never called by bpy. */\n")
        for s in all_syms:
            fh.write(f"void *{s}(void) {{ return (void *)0; }}\n")
        fh.write("extern int _astra_stub_dummy;\nint _astra_stub_dummy = 0;\n")

    for lib in sorted(libs):
        src = os.path.join(stub_dir, "stubs.c")
        dst = os.path.join(stub_dir, lib)
        r = subprocess.run(
            ["gcc", "-shared", "-fPIC", f"-Wl,-soname,{lib}", "-o", dst, src],
            capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"[gfx_stubs] failed to build {lib}:\n{r.stderr}")
    return len(all_syms), sorted(libs)


def bpy_import_env(stub_dir: str) -> dict[str, str]:
    env = dict(os.environ)
    env["LD_LIBRARY_PATH"] = stub_dir + os.pathsep + env.get("LD_LIBRARY_PATH", "")
    return env


def try_import(python_bin: str, env: dict[str, str]):
    """(ok, missing_symbol_or_error)"""
    r = subprocess.run([python_bin, "-c", "import bpy"], env=env, capture_output=True, text=True)
    if r.returncode == 0:
        return True, None
    for line in r.stderr.splitlines():
        if "undefined symbol:" in line:
            return False, line.split("undefined symbol:")[1].split()[0].strip("(),")
    return False, r.stderr.strip().splitlines()[-1]


def main():
    root = os.path.expanduser(os.environ.get("ASTRA_BLENDER_ROOT", "~/env"))
    stub_dir = os.path.expanduser(os.environ.get("ASTRA_GFX_STUBS", "~/gfxstub"))
    python_bin = os.path.join(root, "bin", "python")
    bpy_dir = glob.glob(os.path.join(root, "lib", "python*", "site-packages", "bpy"))
    if not bpy_dir:
        sys.exit("[gfx_stubs] bpy not installed -- run tools/setup_blender_env.sh first")
    bpy_dir = bpy_dir[0]

    missing, want = scan(bpy_dir, python_bin)
    libs = missing | {l for l in ALWAYS_STUB if not _resolvable(l, python_bin)}
    n, built = build(stub_dir, libs, want)
    print(f"[gfx_stubs] {n} symbols -> {len(built)} stub libs: {' '.join(built)}")

    env = bpy_import_env(stub_dir)
    for _ in range(MAX_ROUNDS):
        ok, err = try_import(python_bin, env)
        if ok:
            print("[gfx_stubs] bpy imports cleanly")
            return
        if err is None or err.startswith("No module"):
            sys.exit(f"[gfx_stubs] import failed: {err}")
        print(f"[gfx_stubs] adding late symbol: {err}")
        want = want | {err}
        _rebuild_with(stub_dir, libs, err)

    sys.exit("[gfx_stubs] giving up after too many retries")


def _resolvable(soname: str, python_bin: str) -> bool:
    """True when the real system already provides this library."""
    out = sh(f"ldconfig -p 2>/dev/null | grep -w {soname}")
    return bool(out.strip())


def _rebuild_with(stub_dir: str, libs: set[str], sym: str):
    cache = os.path.join(stub_dir, "symbols.txt")
    with open(cache, "a") as fh:
        fh.write(sym + "\n")
    syms = sorted({l.strip() for l in open(cache) if l.strip()})
    with open(os.path.join(stub_dir, "stubs.c"), "w") as fh:
        fh.write("/* Auto-generated by tools/gfx_stubs.py -- never called by bpy. */\n")
        for s in syms:
            fh.write(f"void *{s}(void) {{ return (void *)0; }}\n")
    for lib in sorted(libs):
        subprocess.run(["gcc", "-shared", "-fPIC", f"-Wl,-soname,{lib}",
                        "-o", os.path.join(stub_dir, lib),
                        os.path.join(stub_dir, "stubs.c")], check=True)


if __name__ == "__main__":
    main()
